import type {
  AssetRecord,
  CustomerPortalRecord,
  DemoDocument,
  DemoJob,
  LeadExample,
  QuoteRequest,
  ShipmentRecord,
} from "./transpak-demo-types";

const VERIFY = "Public research example — verify before outreach.";

export const leadExamples: LeadExample[] = [
  {
    id: "LEAD-001",
    companyName: "Panasonic Energy",
    website: "https://na.panasonic.com",
    city: "De Soto",
    state: "KS",
    category: "Battery/EV",
    industry: "Battery manufacturing",
    publicSignal: "Facility / equipment-heavy business profile — verify before outreach.",
    whyTransPakFit:
      "Large-format battery production moves heavy tooling and sensitive equipment — crating and logistics discipline matters.",
    suggestedServices: ["export packaging", "crating", "distribution", "documentation"],
    salesTalkingPoint:
      "High-value equipment moves benefit from repeatable packaging standards and shipment visibility.",
    nextAction: "Qualify inbound logistics cadence and packaging standards needs.",
    confidenceScore: 88,
    status: "Research",
    sourceLabel: "Public company profile",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-002",
    companyName: "Rivian",
    website: "https://rivian.com",
    city: "Normal",
    state: "IL",
    category: "Battery/EV",
    industry: "EV manufacturing",
    publicSignal: "High-value equipment / regulated shipment fit — verify active need before outreach.",
    whyTransPakFit:
      "EV assembly and battery adjacent flows often require engineered crates and time-sensitive freight coordination.",
    suggestedServices: ["custom crating", "logistics", "customer portal", "kitting"],
    salesTalkingPoint:
      "OEM-scale movement benefits from packaging engineering aligned to carrier constraints.",
    nextAction: "Map plant inbound/outbound equipment patterns before proposing packaging lanes.",
    confidenceScore: 84,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-003",
    companyName: "GE HealthCare",
    website: "https://www.gehealthcare.com",
    city: "Waukesha",
    state: "WI",
    category: "Medical",
    industry: "Medical imaging equipment",
    publicSignal: "Regulated equipment logistics profile — verify before outreach.",
    whyTransPakFit:
      "Imaging systems require documentation-heavy shipment support and protective engineered packaging.",
    suggestedServices: ["crating", "documentation", "export packaging", "inspection photos"],
    salesTalkingPoint:
      "Sensitive modalities need repeatable crate specs and photo checkpoints for release.",
    nextAction: "Identify regions with frequent modality transfers or retrofit cycles.",
    confidenceScore: 91,
    status: "Research",
    sourceLabel: "Public company profile",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-004",
    companyName: "Stryker",
    website: "https://www.stryker.com",
    city: "Kalamazoo",
    state: "MI",
    category: "Medical",
    industry: "Medical devices",
    publicSignal: "Public company profile suggests complex equipment movement — verify before outreach.",
    whyTransPakFit: "Device OEM ecosystems often need sterile-adjacent handling plans and traceable documentation.",
    suggestedServices: ["packaging design", "document handling", "logistics"],
    salesTalkingPoint: "Packaging + documentation discipline reduces release risk on high-value transfers.",
    nextAction: "Confirm regional depot/capital equipment movement patterns.",
    confidenceScore: 86,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-005",
    companyName: "Medtronic",
    website: "https://www.medtronic.com",
    city: "Minneapolis",
    state: "MN",
    category: "Medical",
    industry: "Medical technology",
    publicSignal: "Facility / equipment-heavy business profile — verify before outreach.",
    whyTransPakFit: "Complex supply chains benefit from standardized crate releases and customer-ready updates.",
    suggestedServices: ["kitting", "distribution", "customer portal"],
    salesTalkingPoint: "Multi-site distribution benefits from consistent labeling and wave planning support.",
    nextAction: "Explore kit consolidation opportunities tied to regional hubs.",
    confidenceScore: 83,
    status: "Research",
    sourceLabel: "Public company profile",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-006",
    companyName: "Applied Materials",
    website: "https://www.appliedmaterials.com",
    city: "Santa Clara",
    state: "CA",
    category: "Semiconductor",
    industry: "Semiconductor equipment",
    publicSignal: "High-value equipment / regulated shipment fit — verify active need before outreach.",
    whyTransPakFit: "Tool moves require engineered shock/vibration planning and rigorous documentation.",
    suggestedServices: ["high-value packaging", "engineering review", "export packaging"],
    salesTalkingPoint: "Semiconductor tool transfers need packaging specs aligned to fab receiving standards.",
    nextAction: "Identify routes with frequent tool transfers between fabs and integrators.",
    confidenceScore: 92,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-007",
    companyName: "Lam Research",
    website: "https://www.lamresearch.com",
    city: "Fremont",
    state: "CA",
    category: "Semiconductor",
    industry: "Semiconductor equipment",
    publicSignal: "Public company profile suggests complex equipment movement — verify before outreach.",
    whyTransPakFit: "Process equipment moves benefit from shock-controlled builds and detailed photo checkpoints.",
    suggestedServices: ["custom crating", "documentation", "inspection photos"],
    salesTalkingPoint: "Release gates often depend on photo proof packs matched to customer engineering checklists.",
    nextAction: "Map integrator handoffs where packaging specifications are highest variance.",
    confidenceScore: 89,
    status: "Research",
    sourceLabel: "Public company profile",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-008",
    companyName: "KLA",
    website: "https://www.kla.com",
    city: "Milpitas",
    state: "CA",
    category: "Semiconductor",
    industry: "Process control / inspection",
    publicSignal: "High-value equipment / regulated shipment fit — verify active need before outreach.",
    whyTransPakFit: "Precision tools require moisture barrier discipline and clean-handling packaging patterns.",
    suggestedServices: ["packaging design", "export packaging", "logistics"],
    salesTalkingPoint: "Precision instrumentation benefits from packaging engineered to contamination controls.",
    nextAction: "Qualify shipping lanes with repeated high-value module transfers.",
    confidenceScore: 87,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-009",
    companyName: "Honeywell Aerospace",
    website: "https://aerospace.honeywell.com",
    city: "Phoenix",
    state: "AZ",
    category: "Aerospace",
    industry: "Aerospace systems",
    publicSignal: "Export and compliance-sensitive movement profile — verify before outreach.",
    whyTransPakFit: "Aerospace components often require export documentation packages and strict evidence trails.",
    suggestedServices: ["export crating", "compliance documentation", "customer updates"],
    salesTalkingPoint: "International lanes benefit when packaging and paperwork stay synchronized.",
    nextAction: "Review lanes with recurring export documentation complexity.",
    confidenceScore: 85,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-010",
    companyName: "Northrop Grumman",
    website: "https://www.northropgrumman.com",
    city: "Falls Church",
    state: "VA",
    category: "Defense",
    industry: "Defense / aerospace",
    publicSignal: "Sensitive logistics profile — verify before outreach; follow compliance guardrails.",
    whyTransPakFit: "Defense-adjacent supply chains require disciplined documentation and chain-of-custody patterns.",
    suggestedServices: ["documentation", "secure handling planning", "crating"],
    salesTalkingPoint: "Operational discipline in packaging evidence packs reduces downstream review cycles.",
    nextAction: "Confirm qualification requirements before proposing specific workflows.",
    confidenceScore: 78,
    status: "Research",
    sourceLabel: "Public company profile",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-011",
    companyName: "Boston Dynamics",
    website: "https://www.bostondynamics.com",
    city: "Waltham",
    state: "MA",
    category: "Robotics",
    industry: "Robotics",
    publicSignal: "High-value equipment / regulated shipment fit — verify active need before outreach.",
    whyTransPakFit: "Robotics hardware demos and deployments involve irregular shapes and shock-sensitive payloads.",
    suggestedServices: ["custom crating", "foam engineering", "field updates"],
    salesTalkingPoint: "Dynamic payloads benefit from engineered interior restraints and repeatable photo checkpoints.",
    nextAction: "Explore demo tour logistics and depot refurbishment cycles.",
    confidenceScore: 86,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-012",
    companyName: "Rockwell Automation",
    website: "https://www.rockwellautomation.com",
    city: "Milwaukee",
    state: "WI",
    category: "Industrial",
    industry: "Industrial automation",
    publicSignal: "Facility / equipment-heavy business profile — verify before outreach.",
    whyTransPakFit: "Automation suppliers frequently move large drives, panels, and line components with documentation packs.",
    suggestedServices: ["reverse logistics", "crating", "kitting"],
    salesTalkingPoint: "Trade show and retrofit cycles often need inventory-aligned packaging and labeling.",
    nextAction: "Identify peak seasons for field deployments and returns.",
    confidenceScore: 82,
    status: "Research",
    sourceLabel: "Public company profile",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-013",
    companyName: "Thermo Fisher Scientific",
    website: "https://www.thermofisher.com",
    city: "Waltham",
    state: "MA",
    category: "Lab equipment",
    industry: "Scientific equipment",
    publicSignal: "Public company profile suggests complex equipment movement — verify before outreach.",
    whyTransPakFit: "Lab instrumentation shipments often need certificate alignment and customer-ready updates.",
    suggestedServices: ["distribution", "documentation", "customer portal"],
    salesTalkingPoint: "Multi-site distribution improves when documentation and labeling stay synchronized.",
    nextAction: "Map regional hubs with frequent outbound instrument transfers.",
    confidenceScore: 88,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-014",
    companyName: "Flexential",
    website: "https://www.flexential.com",
    city: "Charlotte",
    state: "NC",
    category: "Data centers",
    industry: "Data center operations",
    publicSignal: "High-value infrastructure movement profile — verify before outreach.",
    whyTransPakFit: "Data center providers frequently coordinate rack-level logistics and time-window deliveries.",
    suggestedServices: ["packaging", "dock coordination", "shipment monitoring"],
    salesTalkingPoint: "Rack moves benefit when dock details and delivery windows are structured early.",
    nextAction: "Identify metros with frequent rack refresh cycles.",
    confidenceScore: 81,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-015",
    companyName: "QTS Data Centers",
    website: "https://www.qtsdatacenters.com",
    city: "Overland Park",
    state: "KS",
    category: "Data centers",
    industry: "Data center operations",
    publicSignal: "Facility / equipment-heavy business profile — verify before outreach.",
    whyTransPakFit: "Facility expansions often imply inbound OEM racks and accessories requiring coordinated receiving.",
    suggestedServices: ["logistics support", "packaging", "customer updates"],
    salesTalkingPoint: "Inbound rack logistics benefits from photo checkpoints and receiving alignment.",
    nextAction: "Explore regional construction/expansion activity responsibly via public sources.",
    confidenceScore: 79,
    status: "Research",
    sourceLabel: "Public research",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-016",
    companyName: "Schneider Electric",
    website: "https://www.se.com",
    city: "Andover",
    state: "MA",
    category: "Industrial",
    industry: "Energy & automation equipment",
    publicSignal: "Public company profile suggests complex equipment movement — verify before outreach.",
    whyTransPakFit: "Electrical gear movements often need documented packing lists and export readiness.",
    suggestedServices: ["kitting", "distribution", "export packaging"],
    salesTalkingPoint: "Multi-site kitting improves when labels and packing lists match wave schedules.",
    nextAction: "Identify partner distributor lanes with multi-stop deliveries.",
    confidenceScore: 84,
    status: "Research",
    sourceLabel: "Public company profile",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-017",
    companyName: "Siemens Healthineers",
    website: "https://www.siemens-healthineers.com",
    city: "Malvern",
    state: "PA",
    category: "Medical",
    industry: "Medical imaging / diagnostics",
    publicSignal: "Regulated equipment logistics profile — verify before outreach.",
    whyTransPakFit: "Diagnostics supply chains require disciplined documentation and customer-safe messaging.",
    suggestedServices: ["documentation", "customer portal", "crating"],
    salesTalkingPoint: "Customer-ready updates reduce inbound status inquiries during long transfers.",
    nextAction: "Map modality movement lanes where documentation variance is highest.",
    confidenceScore: 87,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
  {
    id: "LEAD-018",
    companyName: "ABB Robotics",
    website: "https://new.abb.com/products/robotics",
    city: "Auburn Hills",
    state: "MI",
    category: "Robotics",
    industry: "Industrial robotics",
    publicSignal: "High-value equipment / regulated shipment fit — verify active need before outreach.",
    whyTransPakFit: "Robot cells and line components often require urgent lanes with engineered packaging.",
    suggestedServices: ["rush crating", "logistics", "field updates"],
    salesTalkingPoint: "Replacement part programs benefit when crate release gates match carrier cutoffs.",
    nextAction: "Explore aftermarket parts velocity patterns regionally.",
    confidenceScore: 85,
    status: "Research",
    sourceLabel: "Industry footprint",
    disclaimer: VERIFY,
  },
];

export const demoJobs: DemoJob[] = [
  {
    id: "TPK-1001",
    customerId: "CUST-BD",
    customerName: "Alex Rivera",
    companyName: "Boston Dynamics Demo Account",
    serviceType: "Custom crating / export packaging",
    title: "Custom Crate for Industrial Robot Arm",
    description: "High-value robotic component requiring shock protection and staged photo checkpoints.",
    dimensions: "96 in x 48 in x 62 in",
    weight: "1,850 lb",
    origin: "Waltham, MA",
    destination: "San Jose, CA",
    assignedDepartment: "Packaging engineering",
    assignedOwner: "Jordan Lee",
    status: "In shop review",
    priority: "High",
    dueDate: "2026-05-18",
    requiredDocuments: ["quote approval", "packing spec", "inspection photos", "BOL"],
    requiredPhotos: ["pre-pack", "foam placement", "strapping", "crate markings", "final loaded"],
    blockers: ["awaiting final weight confirmation"],
    aiSummary:
      "High-value robotic component requires shock protection, photo checkpoints, and human approval before release.",
    nextBestAction: "Confirm final weight and assign photo checkpoint checklist.",
    qrRoute: "/jobs/TPK-1001",
    customerPortalRoute: "/portal/CUST-BD",
    photos: ["pre-pack-001.jpg", "foam-002.jpg"],
    updates: [{ at: "2026-05-02T14:00:00Z", label: "Inspection", detail: "Initial crate inspection started." }],
    timeline: [
      { at: "2026-05-01T10:00:00Z", label: "Intake", detail: "Job created from approved quote." },
      { at: "2026-05-02T14:00:00Z", label: "Shop", detail: "Foam layout reviewed by lead tech." },
    ],
  },
  {
    id: "TPK-1002",
    customerId: "CUST-QTS",
    customerName: "Sam Patel",
    companyName: "QTS Data Centers Demo Account",
    serviceType: "Packaging / logistics support",
    title: "Data Center Server Rack Packaging",
    description: "Server rack shipment needs dock access confirmation and protective packaging plan.",
    dimensions: "84 in x 30 in x 48 in",
    weight: "900 lb",
    origin: "Overland Park, KS",
    destination: "Irving, TX",
    assignedDepartment: "Logistics",
    assignedOwner: "Taylor Brooks",
    status: "Quote intake",
    priority: "Medium",
    dueDate: "2026-05-22",
    requiredDocuments: ["BOL", "packing list", "photos", "carrier confirmation"],
    requiredPhotos: ["rack condition", "wrap", "labels", "loaded"],
    blockers: ["missing destination dock details"],
    aiSummary: "Server rack shipment needs dock access confirmation and protective packaging plan before quote finalization.",
    nextBestAction: "Request destination dock details and preferred delivery window.",
    qrRoute: "/jobs/TPK-1002",
    customerPortalRoute: "/portal/CUST-QTS",
    photos: [],
    updates: [],
    timeline: [{ at: "2026-05-03T09:00:00Z", label: "Quote", detail: "Estimator reviewing rack handling assumptions." }],
  },
  {
    id: "TPK-1003",
    customerId: "CUST-GE",
    customerName: "Morgan Chen",
    companyName: "GE HealthCare Demo Account",
    serviceType: "Crating / documentation / shipment support",
    title: "Medical Imaging Equipment Shipment",
    description: "Sensitive medical equipment job with documentation gates prior to release.",
    dimensions: "72 in x 54 in x 68 in",
    weight: "2,400 lb",
    origin: "Waukesha, WI",
    destination: "Phoenix, AZ",
    assignedDepartment: "Compliance",
    assignedOwner: "Riley Nguyen",
    status: "Documentation review",
    priority: "High",
    dueDate: "2026-05-14",
    requiredDocuments: ["certificate", "inspection photos", "BOL", "packing list"],
    requiredPhotos: ["serial plate", "accessory kit", "crate interior", "final seal"],
    blockers: ["certificate missing"],
    aiSummary: "Sensitive medical equipment job requires complete documentation before release.",
    nextBestAction: "Add certificate to document hub and confirm accessory list.",
    qrRoute: "/jobs/TPK-1003",
    customerPortalRoute: "/portal/CUST-GE",
    photos: ["serial-plate-010.jpg"],
    updates: [],
    timeline: [{ at: "2026-05-02T11:30:00Z", label: "Docs", detail: "Document package assembled pending certificate." }],
  },
  {
    id: "TPK-1004",
    customerId: "CUST-HON",
    customerName: "Casey Frost",
    companyName: "Honeywell Aerospace Demo Account",
    serviceType: "Export crating / compliance checklist",
    title: "Aerospace Component Export Crate",
    description: "Export shipment requiring compliance checklist completion and photo proof.",
    dimensions: "52 in x 40 in x 38 in",
    weight: "620 lb",
    origin: "Phoenix, AZ",
    destination: "Hamburg, Germany",
    assignedDepartment: "Compliance",
    assignedOwner: "Jamie Ortiz",
    status: "Compliance hold",
    priority: "High",
    dueDate: "2026-05-12",
    requiredDocuments: ["export packing list", "customs docs", "certificate", "BOL"],
    requiredPhotos: ["part condition", "moisture barrier", "crate markings", "final seal"],
    blockers: ["customs checklist incomplete"],
    aiSummary: "Export shipment needs compliance checklist completion and final photo proof before handoff.",
    nextBestAction: "Complete customs checklist and route to compliance review.",
    qrRoute: "/jobs/TPK-1004",
    customerPortalRoute: "/portal/CUST-HON",
    photos: [],
    updates: [],
    timeline: [{ at: "2026-05-01T16:10:00Z", label: "Hold", detail: "Compliance review flagged incomplete checklist." }],
  },
  {
    id: "TPK-1005",
    customerId: "CUST-AMAT",
    customerName: "Priya Shah",
    companyName: "Applied Materials Demo Account",
    serviceType: "High-value equipment packaging",
    title: "Semiconductor Tool Packaging",
    description: "Semiconductor tool requiring engineering confirmation for vibration and shock controls.",
    dimensions: "110 in x 72 in x 80 in",
    weight: "4,200 lb",
    origin: "Santa Clara, CA",
    destination: "Austin, TX",
    assignedDepartment: "Engineering",
    assignedOwner: "Chris Dalton",
    status: "Engineering review",
    priority: "Critical",
    dueDate: "2026-05-20",
    requiredDocuments: ["packing spec", "vibration requirement", "BOL", "inspection photos"],
    requiredPhotos: ["base restraint", "foam", "sensors", "crate exterior"],
    blockers: ["vibration requirement not confirmed"],
    aiSummary: "High-value semiconductor equipment requires engineering confirmation before shop release.",
    nextBestAction: "Confirm vibration/shock requirements and create packaging spec.",
    qrRoute: "/jobs/TPK-1005",
    customerPortalRoute: "/portal/CUST-AMAT",
    photos: [],
    updates: [],
    timeline: [{ at: "2026-05-03T08:45:00Z", label: "Engineering", detail: "Awaiting customer vibration profile." }],
  },
  {
    id: "TPK-1006",
    customerId: "CUST-ROK",
    customerName: "Drew Maxwell",
    companyName: "Rockwell Automation Demo Account",
    serviceType: "Reverse logistics / packaging",
    title: "Trade Show Equipment Return Logistics",
    description: "Multi-piece return job requiring inventory match and photo proof before pickup.",
    dimensions: "multiple crates",
    weight: "3,800 lb combined",
    origin: "Las Vegas, NV",
    destination: "Milwaukee, WI",
    assignedDepartment: "Distribution",
    assignedOwner: "Samira Wolf",
    status: "Ready for pickup",
    priority: "Medium",
    dueDate: "2026-05-09",
    requiredDocuments: ["inventory sheet", "BOL", "condition photos"],
    requiredPhotos: ["booth components", "crate labels", "loaded pallets"],
    blockers: [],
    aiSummary: "Multi-piece return job needs inventory match and photo proof before carrier pickup.",
    nextBestAction: "Confirm all labels against inventory sheet.",
    qrRoute: "/jobs/TPK-1006",
    customerPortalRoute: "/portal/CUST-ROK",
    photos: ["inventory-204.jpg"],
    updates: [],
    timeline: [{ at: "2026-05-04T07:20:00Z", label: "Staging", detail: "Crates staged for carrier window." }],
  },
  {
    id: "TPK-1007",
    customerId: "CUST-SCH",
    customerName: "Noah Ibrahim",
    companyName: "Schneider Electric Demo Account",
    serviceType: "Kitting / packaging / distribution",
    title: "High-Value Electronics Kitting Project",
    description: "Multi-site kitting job pending final destination list for wave planning.",
    dimensions: "mixed SKUs",
    weight: "1,200 lb combined",
    origin: "Andover, MA",
    destination: "Multiple US sites",
    assignedDepartment: "Distribution",
    assignedOwner: "Mel Carter",
    status: "Distribution planning",
    priority: "Medium",
    dueDate: "2026-05-25",
    requiredDocuments: ["SKU list", "packing list", "shipment schedule"],
    requiredPhotos: ["kit layout", "label set", "outbound pallets"],
    blockers: ["final site list pending"],
    aiSummary: "Multi-site kitting job requires final destination list before wave planning.",
    nextBestAction: "Request final site list and schedule distribution wave.",
    qrRoute: "/jobs/TPK-1007",
    customerPortalRoute: "/portal/CUST-SCH",
    photos: [],
    updates: [],
    timeline: [{ at: "2026-05-02T18:00:00Z", label: "Planning", detail: "Wave plan pending site confirmations." }],
  },
  {
    id: "TPK-1008",
    customerId: "CUST-ABB",
    customerName: "Rhea Collins",
    companyName: "ABB Robotics Demo Account",
    serviceType: "Rush crating / logistics",
    title: "Urgent Replacement Part Shipment",
    description: "Rush replacement shipment with time-sensitive carrier cutoff.",
    dimensions: "48 in x 36 in x 30 in",
    weight: "310 lb",
    origin: "Auburn Hills, MI",
    destination: "Nashville, TN",
    assignedDepartment: "Operations",
    assignedOwner: "Logan Hayes",
    status: "Urgent",
    priority: "Critical",
    dueDate: "2026-05-06",
    requiredDocuments: ["BOL", "rush approval", "carrier confirmation"],
    requiredPhotos: ["part condition", "final package", "loaded shipment"],
    blockers: ["carrier cutoff approaching"],
    aiSummary: "Rush replacement shipment has time-sensitive carrier cutoff and requires immediate staging.",
    nextBestAction: "Move job to urgent lane and confirm carrier pickup.",
    qrRoute: "/jobs/TPK-1008",
    customerPortalRoute: "/portal/CUST-ABB",
    photos: [],
    updates: [],
    timeline: [{ at: "2026-05-05T12:00:00Z", label: "Urgent", detail: "Escalated due to carrier cutoff." }],
  },
  {
    id: "TPK-1009",
    customerId: "CUST-TFS",
    customerName: "Harper Lin",
    companyName: "Thermo Fisher Scientific Demo Account",
    serviceType: "Distribution / documentation",
    title: "Multi-Site Distribution Job",
    description: "Distribution job progressing but missing contacts for two delivery sites.",
    dimensions: "multiple packages",
    weight: "2,700 lb combined",
    origin: "Waltham, MA",
    destination: "6 regional sites",
    assignedDepartment: "Distribution",
    assignedOwner: "Emma Duarte",
    status: "In progress",
    priority: "Medium",
    dueDate: "2026-05-30",
    requiredDocuments: ["site list", "packing slips", "BOLs", "certificates"],
    requiredPhotos: ["each outbound group", "labels", "staged pallets"],
    blockers: ["two site contacts missing"],
    aiSummary: "Distribution job is progressing but missing contacts for two delivery sites.",
    nextBestAction: "Resolve missing site contacts before dispatch.",
    qrRoute: "/jobs/TPK-1009",
    customerPortalRoute: "/portal/CUST-TFS",
    photos: [],
    updates: [],
    timeline: [{ at: "2026-05-03T15:15:00Z", label: "Dispatch prep", detail: "Wave 1 staged; two contacts outstanding." }],
  },
  {
    id: "TPK-1010",
    customerId: "CUST-PANA",
    customerName: "Chris Nolan",
    companyName: "Panasonic Energy Demo Account",
    serviceType: "Inspection / documentation / claim support",
    title: "Damaged Incoming Freight Inspection",
    description: "Incoming freight exception needs documented photo proof and claim-ready summary.",
    dimensions: "60 in x 48 in x 48 in",
    weight: "760 lb",
    origin: "De Soto, KS",
    destination: "TransPak demo facility",
    assignedDepartment: "Quality",
    assignedOwner: "Pat Silva",
    status: "Exception",
    priority: "High",
    dueDate: "2026-05-08",
    requiredDocuments: ["inbound BOL", "damage photos", "inspection report"],
    requiredPhotos: ["exterior damage", "contents", "labels", "closeups"],
    blockers: ["damage report pending"],
    aiSummary: "Incoming freight exception needs documented photo proof and claim-ready summary.",
    nextBestAction: "Complete inspection report and generate customer update draft.",
    qrRoute: "/jobs/TPK-1010",
    customerPortalRoute: "/portal/CUST-PANA",
    photos: ["damage-001.jpg"],
    updates: [],
    timeline: [{ at: "2026-05-04T09:40:00Z", label: "Exception", detail: "Inspection opened for inbound damage." }],
  },
];

export const assetRecords: AssetRecord[] = [
  {
    id: "FORKLIFT-04",
    assetType: "MHE",
    name: "Forklift — Bay 04",
    facility: "Chicago Plant",
    location: "Receiving lane B",
    status: "Operational",
    lastService: "2026-04-18",
    openIssues: [],
    qrRoute: "/assets/FORKLIFT-04",
    maintenanceNotes: ["Quarterly inspection logged", "Tire wear within tolerance"],
    aiSummary: "Stable operational profile; watch brake response during peak inbound windows.",
    nextBestAction: "Schedule preventative maintenance after next 120 lift cycles.",
  },
  {
    id: "CNC-01",
    assetType: "CNC",
    name: "CNC Router — Cell 01",
    facility: "Chicago Plant",
    location: "Fabrication floor",
    status: "Needs calibration",
    lastService: "2026-03-22",
    openIssues: ["Spindle vibration above baseline on long runs"],
    qrRoute: "/assets/CNC-01",
    maintenanceNotes: ["Vibration spike observed on 45+ minute jobs"],
    aiSummary: "Vibration trend suggests spindle inspection before next high-tolerance job.",
    nextBestAction: "Pull spindle diagnostics and compare against baseline signature.",
  },
  {
    id: "PANEL-SAW-02",
    assetType: "Saw",
    name: "Panel Saw — Line 02",
    facility: "Chicago Plant",
    location: "Wood shop",
    status: "Operational",
    lastService: "2026-04-29",
    openIssues: [],
    qrRoute: "/assets/PANEL-SAW-02",
    maintenanceNotes: ["Blade replaced", "Fence calibration verified"],
    aiSummary: "Healthy cutting profile; maintain fence calibration schedule.",
    nextBestAction: "Confirm dust collection differential pressure weekly.",
  },
  {
    id: "COMPRESSOR-03",
    assetType: "Compressed air",
    name: "Compressor Bank — 03",
    facility: "Chicago Plant",
    location: "Mechanical yard",
    status: "Watch",
    lastService: "2026-04-10",
    openIssues: ["Intermittent pressure dip under simultaneous bay loads"],
    qrRoute: "/assets/COMPRESSOR-03",
    maintenanceNotes: ["Dryer service due", "Leak scan scheduled"],
    aiSummary: "Pressure dips correlate with concurrent bay peaks — verify capacity vs demand.",
    nextBestAction: "Run leak detection and validate dryer performance metrics.",
  },
  {
    id: "STRAPPER-07",
    assetType: "Strapper",
    name: "Automatic Strapper — Lane 07",
    facility: "Chicago Plant",
    location: "Outbound staging",
    status: "Operational",
    lastService: "2026-05-01",
    openIssues: [],
    qrRoute: "/assets/STRAPPER-07",
    maintenanceNotes: ["Head temperature stable", "Film tension nominal"],
    aiSummary: "Outbound strap quality stable; monitor film tension during humidity swings.",
    nextBestAction: "Keep spare strap head kit staged during peak outbound weeks.",
  },
];

export const shipmentRecords: ShipmentRecord[] = [
  {
    id: "SHP-2207",
    jobId: "TPK-1001",
    carrier: "RoadLink Freight",
    origin: "Waltham, MA",
    destination: "San Jose, CA",
    status: "Staging",
    priority: "High",
    eta: "2026-05-16",
    requiredDocuments: ["BOL", "packing list", "photos"],
    missingDocuments: [],
    blockers: ["awaiting final weight confirmation"],
    riskLevel: "Medium",
    qrRoute: "/shipments/SHP-2207",
    aiSummary: "Lane is stable; risk rises if weight variance forces reload planning.",
    nextBestAction: "Confirm weight before carrier booking finalization.",
  },
  {
    id: "SHP-2208",
    jobId: "TPK-1002",
    carrier: "Midwest LTL",
    origin: "Overland Park, KS",
    destination: "Irving, TX",
    status: "Quote dependent",
    priority: "Medium",
    eta: "TBD",
    requiredDocuments: ["BOL", "dock appointment"],
    missingDocuments: ["dock appointment"],
    blockers: ["missing destination dock details"],
    riskLevel: "Medium",
    qrRoute: "/shipments/SHP-2208",
    aiSummary: "Scheduling risk until dock details and appointment window are captured.",
    nextBestAction: "Collect dock contact and appointment confirmation.",
  },
  {
    id: "SHP-2209",
    jobId: "TPK-1003",
    carrier: "Pacific Express",
    origin: "Waukesha, WI",
    destination: "Phoenix, AZ",
    status: "Documentation hold",
    priority: "High",
    eta: "2026-05-13",
    requiredDocuments: ["certificate", "BOL"],
    missingDocuments: ["certificate"],
    blockers: ["certificate missing"],
    riskLevel: "High",
    qrRoute: "/shipments/SHP-2209",
    aiSummary: "Documentation gap is the primary shipment risk factor.",
    nextBestAction: "Attach certificate and refresh release checklist.",
  },
  {
    id: "SHP-2210",
    jobId: "TPK-1004",
    carrier: "Global Atlantic Freight",
    origin: "Phoenix, AZ",
    destination: "Hamburg, DE",
    status: "Compliance review",
    priority: "High",
    eta: "2026-05-17",
    requiredDocuments: ["customs pack", "export checklist"],
    missingDocuments: ["export checklist"],
    blockers: ["customs checklist incomplete"],
    riskLevel: "High",
    qrRoute: "/shipments/SHP-2210",
    aiSummary: "International lane risk concentrates in export checklist completeness.",
    nextBestAction: "Complete customs checklist and attach supporting documents.",
  },
  {
    id: "SHP-2211",
    jobId: "TPK-1008",
    carrier: "ExpressNorth",
    origin: "Auburn Hills, MI",
    destination: "Nashville, TN",
    status: "Urgent pickup",
    priority: "Critical",
    eta: "2026-05-06",
    requiredDocuments: ["BOL", "rush approval"],
    missingDocuments: [],
    blockers: ["carrier cutoff approaching"],
    riskLevel: "High",
    qrRoute: "/shipments/SHP-2211",
    aiSummary: "Time risk dominates — prioritize staging verification and carrier confirmation.",
    nextBestAction: "Confirm pickup window within next 2 hours.",
  },
];

export const quoteRequests: QuoteRequest[] = [
  {
    id: "QUOTE-501",
    receivedAt: "2026-05-04T13:22:00Z",
    customerName: "Jamie Alvarez",
    companyName: "Northern Automation Labs",
    email: "jalvarez@example.com",
    phone: "(555) 010-2211",
    serviceType: "Custom crating",
    productDescription: "Precision automation module — shock-sensitive, dense core.",
    dimensions: "62 x 44 x 38 in",
    weight: "980 lb",
    origin: "Chicago, IL",
    destination: "Portland, OR",
    urgency: "Standard",
    requestedDate: "2026-05-12",
    notes: "Needs moisture barrier and tilt indicators.",
    uploadedFiles: ["module_photo_01.png", "datasheet.pdf"],
    aiSummary:
      "Structured intake suggests engineered foam strategy with tilt monitoring; confirm lifting points and CG constraints.",
    missingFields: ["confirmed pickup window", "dock hours at destination"],
    riskFlags: ["unclear CG marking", "temperature sensitivity unknown"],
    suggestedNextStep: "Request lifting diagram and confirm destination dock constraints.",
    approvalStatus: "pending",
  },
  {
    id: "QUOTE-502",
    receivedAt: "2026-05-03T17:05:00Z",
    customerName: "Taylor Singh",
    companyName: "Lakeview Controls",
    email: "tsingh@example.com",
    phone: "(555) 010-8844",
    serviceType: "Kitting + distribution",
    productDescription: "Replacement kits for regional installs — mixed SKUs.",
    dimensions: "mixed",
    weight: "1,450 lb combined",
    origin: "Milwaukee, WI",
    destination: "Multiple regions",
    urgency: "Expedited",
    requestedDate: "2026-05-09",
    notes: "Customer wants labeled pallets per site.",
    uploadedFiles: ["sku_list.xlsx"],
    aiSummary:
      "Wave-planning job — biggest gap is final site list and receiving contacts per location.",
    missingFields: ["final site list", "two receiving contacts"],
    riskFlags: ["partial address list"],
    suggestedNextStep: "Collect complete site roster before locking carrier assignments.",
    approvalStatus: "needs_info",
  },
];

export const demoDocuments: DemoDocument[] = [
  {
    id: "DOC-9001",
    name: "Bill of lading",
    jobId: "TPK-1001",
    jobTitle: "Custom Crate for Industrial Robot Arm",
    status: "needs_review",
    aiExtractionSummary: "Carrier SCAC present; shipper/consignee names align to demo records.",
    missingFields: ["final declared weight"],
    nextAction: "Update weight after final crate verification.",
  },
  {
    id: "DOC-9002",
    name: "Packing list",
    jobId: "TPK-1006",
    jobTitle: "Trade Show Equipment Return Logistics",
    status: "approved",
    aiExtractionSummary: "Inventory lines match staged crates in photo set.",
    missingFields: [],
    nextAction: "Archive after pickup confirmation.",
  },
  {
    id: "DOC-9003",
    name: "Inspection certificate",
    jobId: "TPK-1003",
    jobTitle: "Medical Imaging Equipment Shipment",
    status: "missing",
    aiExtractionSummary: "Certificate not located in document hub upload batch.",
    missingFields: ["certificate file", "issuer signature block"],
    nextAction: "Request certificate upload from customer package owner.",
  },
  {
    id: "DOC-9004",
    name: "Customs checklist",
    jobId: "TPK-1004",
    jobTitle: "Aerospace Component Export Crate",
    status: "needs_review",
    aiExtractionSummary: "Four checklist items incomplete; harmonized code needs verification.",
    missingFields: ["HS code confirmation"],
    nextAction: "Route to compliance reviewer for HS validation.",
  },
  {
    id: "DOC-9005",
    name: "Insurance certificate",
    jobId: "TPK-1005",
    jobTitle: "Semiconductor Tool Packaging",
    status: "ready",
    aiExtractionSummary: "Coverage limits align with declared value band for demo scenario.",
    missingFields: [],
    nextAction: "Attach to release packet after engineering sign-off.",
  },
  {
    id: "DOC-9006",
    name: "Inspection photos (bundle)",
    jobId: "TPK-1010",
    jobTitle: "Damaged Incoming Freight Inspection",
    status: "needs_review",
    aiExtractionSummary: "Damage severity tagging suggests corner-impact hypothesis — human review recommended.",
    missingFields: ["final inspection disposition"],
    nextAction: "Complete inspection worksheet and finalize claim narrative.",
  },
];

export const customerPortalRecords: CustomerPortalRecord[] = [
  {
    customerId: "CUST-BD",
    companyName: "Boston Dynamics Demo Account",
    contactName: "Alex Rivera",
    visibleJobs: ["TPK-1001"],
    visibleShipments: ["SHP-2207"],
    documents: [
      { name: "Packing overview", status: "Available" },
      { name: "Photo checkpoints", status: "In progress" },
    ],
    updates: [
      { at: "2026-05-02", text: "Crate inspection started; foam layout reviewed." },
      { at: "2026-05-04", text: "Awaiting final weight confirmation before carrier booking." },
    ],
    portalRoute: "/portal/CUST-BD",
    assignedContact: "Jordan Lee — Packaging engineering",
    openIssues: ["Final weight confirmation pending"],
  },
  {
    customerId: "CUST-001",
    companyName: "Demo Aggregate Customer",
    contactName: "Jordan Lee",
    visibleJobs: ["TPK-1001", "TPK-1008"],
    visibleShipments: ["SHP-2207", "SHP-2211"],
    documents: [
      { name: "Shipment docs", status: "Available" },
      { name: "Insurance certificate", status: "Pending" },
    ],
    updates: [{ at: "2026-05-05", text: "Urgent lane monitoring — pickup window tightening." }],
    portalRoute: "/portal/CUST-001",
    assignedContact: "TransPak Demo Coordinator",
    openIssues: ["Carrier cutoff approaching on urgent lane"],
  },
  {
    customerId: "CUST-QTS",
    companyName: "QTS Data Centers Demo Account",
    contactName: "Sam Patel",
    visibleJobs: ["TPK-1002"],
    visibleShipments: ["SHP-2208"],
    documents: [{ name: "Dock details request", status: "Waiting on customer" }],
    updates: [{ at: "2026-05-03", text: "Quote intake paused pending dock details." }],
    portalRoute: "/portal/CUST-QTS",
    assignedContact: "Taylor Brooks — Logistics",
    openIssues: ["Destination dock details missing"],
  },
  {
    customerId: "CUST-GE",
    companyName: "GE HealthCare Demo Account",
    contactName: "Morgan Chen",
    visibleJobs: ["TPK-1003"],
    visibleShipments: ["SHP-2209"],
    documents: [{ name: "Certificate", status: "Missing" }],
    updates: [{ at: "2026-05-02", text: "Documentation review in progress." }],
    portalRoute: "/portal/CUST-GE",
    assignedContact: "Riley Nguyen — Compliance",
    openIssues: ["Certificate not yet uploaded"],
  },
];
